#!/usr/bin/env python3

# ------------------------------------------------------------
# Python standard libraries
# ------------------------------------------------------------

import csv


# ------------------------------------------------------------
# ROS 2 libraries
# ------------------------------------------------------------

import rclpy
from rclpy.node import Node

# Float64MultiArray lets us publish a list of floating-point
# numbers in a ROS 2 topic.
from std_msgs.msg import Float64MultiArray


# ------------------------------------------------------------
# CSV FILE LOCATION
# ------------------------------------------------------------

# This is the CSV generated by sydney_coverage.py.
#
# The CSV contains:
#
# waypoint_id, x, y
# 0,          -533, 161
# 1,          -531, 163
# 2,          -529, 163
#
# These X/Y values are currently the world/map coordinates
# generated by the coverage planner.
CSV_PATH = (
    '/home/bot/vrx_ws/src/planner/'
    'planner/ky_py_pkg/output/'
    'sydney_coverage_path.csv'
)


# ============================================================
# PLANNER NODE
# ============================================================

class PlannerNode(Node):

    # --------------------------------------------------------
    # Constructor
    # --------------------------------------------------------
    #
    # __init__() runs automatically when we create:
    #
    #     node = PlannerNode()
    #
    # It sets up everything the planner needs.
    #
    def __init__(self):

        # Create the ROS 2 node.
        #
        # The name of this node will be:
        #
        #     planner_node
        #
        super().__init__('planner_node')


        # ----------------------------------------------------
        # ROS PUBLISHER
        # ----------------------------------------------------

        # Create a publisher.
        #
        # Message type:
        #     Float64MultiArray
        #
        # Topic:
        #     /planner/waypoints
        #
        # Queue size:
        #     10
        #
        # At this stage we are only testing the communication
        # between our planner and ROS 2.
        self.publisher = self.create_publisher(
            Float64MultiArray,
            '/planner/waypoints',
            10
        )


        # ----------------------------------------------------
        # LOAD THE CSV
        # ----------------------------------------------------

        # Read the CSV and store all waypoints in memory.
        #
        # Example result:
        #
        # [
        #     [0, -533.0, 161.0],
        #     [1, -531.0, 163.0],
        #     [2, -529.0, 163.0],
        #     ...
        # ]
        #
        self.path_array = self.load_csv()


        # Tell us that the node has started.
        self.get_logger().info(
            'Planner node started.'
        )


        # Tell us how many waypoints were loaded.
        self.get_logger().info(
            f'Loaded {len(self.path_array)} waypoints from CSV.'
        )


        # If the CSV is not empty, print the first waypoint.
        #
        # This is useful for checking that the CSV was loaded
        # correctly.
        if len(self.path_array) > 0:

            self.get_logger().info(
                f'First waypoint: {self.path_array[0]}'
            )


        # ----------------------------------------------------
        # TIMER
        # ----------------------------------------------------

        # Call publish_path() every 1 second.
        #
        # We use a timer instead of publishing only once,
        # because a subscriber may start after this node.
        #
        # Every second:
        #
        #     publish_path()
        #
        self.timer = self.create_timer(
            1.0,
            self.publish_path
        )


    # ========================================================
    # LOAD CSV
    # ========================================================

    def load_csv(self):

        # This list will contain all waypoints.
        path_array = []


        # Open the CSV file.
        #
        # newline='' is recommended when using Python's csv
        # module.
        with open(
            CSV_PATH,
            'r',
            newline=''
        ) as csv_file:


            # DictReader uses the first row as column names.
            #
            # Our CSV has:
            #
            # waypoint_id,x,y
            #
            # Therefore we can access:
            #
            # row['waypoint_id']
            # row['x']
            # row['y']
            #
            reader = csv.DictReader(csv_file)


            # Read every row in the CSV.
            for row in reader:

                # Convert waypoint ID from text to integer.
                waypoint_id = int(
                    row['waypoint_id']
                )


                # Convert X from text to float.
                x = float(
                    row['x']
                )


                # Convert Y from text to float.
                y = float(
                    row['y']
                )


                # Store one waypoint as:
                #
                # [ID, X, Y]
                #
                path_array.append(
                    [waypoint_id, x, y]
                )


        # Return all waypoints to __init__().
        return path_array


    # ========================================================
    # PUBLISH PATH
    # ========================================================

    def publish_path(self):

        # Tell us that this function is being called.
        self.get_logger().info(
            'Publishing waypoint array...'
        )


        # Create an empty ROS message.
        msg = Float64MultiArray()


        # Go through every waypoint.
        #
        # Example:
        #
        # [0, -533.0, 161.0]
        # [1, -531.0, 163.0]
        #
        for waypoint in self.path_array:

            # Add the waypoint values to the ROS message.
            #
            # Float64MultiArray is one-dimensional, so the
            # result becomes:
            #
            # [0, -533, 161, 1, -531, 163, ...]
            #
            msg.data.extend(
                waypoint
            )


        # Publish the complete array.
        self.publisher.publish(
            msg
        )


        # Print confirmation.
        self.get_logger().info(
            f'Published {len(self.path_array)} waypoints.'
        )


# ============================================================
# MAIN
# ============================================================

def main(args=None):

    # Start the ROS 2 communication system.
    rclpy.init(args=args)


    # Create our planner node.
    node = PlannerNode()


    # Keep the node running.
    #
    # This allows:
    # - the timer to run
    # - the publisher to publish
    # - ROS 2 callbacks to execute
    #
    rclpy.spin(node)


    # When the node is stopped, clean it up.
    node.destroy_node()


    # Shut down ROS 2.
    rclpy.shutdown()


# ------------------------------------------------------------
# Python entry point
# ------------------------------------------------------------

# Only call main() when this file is executed directly.
#
# This is what eventually starts:
#
#     PlannerNode()
#
if __name__ == '__main__':
    main()